### PR TITLE
AsyncStorage is now imported from the correct package

### PR DESCRIPTION
**Pull request by Chinchila01**

### CODE REVIEW

**Comment by mars-lan** [comment]
@michaelcontento can we merge this in?

**Comment by michaelcontento** [comment]
@mars-lan I'm no longer maintaining this package - sorry :-( 

@guns2410 / @ptomasroos Can you have a look at this?

**Comment by ptomasroos** [comment]
@michaelcontento of course! But I still haven’t any npm rights on this package since the transfer

**Comment by michaelcontento** [comment]
@ptomasroos / @guns2410 Can you provide me with your NPM user names?

**Comment by ptomasroos** [comment]
@michaelcontento https://www.npmjs.com/~ptomasroos

**Comment by michaelcontento** [comment]
@ptomasroos access should be granted to all redux-storage related packages on npm

**Comment by ptomasroos** [comment]
Thanks. Then I will review this on Monday and move on!

**Comment by mars-lan** [comment]
@ptomasroos please release a new version on npm thanks.

**Pull request merged**
